// <auto-generated />
using DynamicQuestionApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicQuestionApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241110082852_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicQuestionApp.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Paris",
                            Options = "[\"Paris\",\"London\",\"Berlin\",\"Rome\"]",
                            OptionsJson = "[\"Paris\",\"London\",\"Berlin\",\"Rome\"]",
                            Text = "What is the capital of France?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Mars",
                            Options = "[\"Earth\",\"Mars\",\"Jupiter\",\"Saturn\"]",
                            OptionsJson = "[\"Earth\",\"Mars\",\"Jupiter\",\"Saturn\"]",
                            Text = "Which planet is known as the Red Planet?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
