// <auto-generated />
using DynamicQuestionApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DynamicQuestionApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DynamicQuestionApp.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Paris",
                            Options = "[\"Paris\",\"London\",\"Berlin\",\"Rome\"]",
                            OptionsJson = "[\"Paris\",\"London\",\"Berlin\",\"Rome\"]",
                            Text = "What is the capital of France?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Yuan",
                            Options = "[\"Yuan\",\"Yen\",\"Dollar\",\"Taka\"]",
                            OptionsJson = "[\"Yuan\",\"Yen\",\"Dollar\",\"Taka\"]",
                            Text = "What is the currency of China?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Amazon",
                            Options = "[\"Amazon\",\"Sundarbans\",\"Black Forest\",\"Africa\"]",
                            OptionsJson = "[\"Amazon\",\"Sundarbans\",\"Black Forest\",\"Africa\"]",
                            Text = "What is the largest rainforest in the world?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Riyadh",
                            Options = "[\"Zedda\",\"Riyadh\",\"Mecca\",\"Medina\"]",
                            OptionsJson = "[\"Zedda\",\"Riyadh\",\"Mecca\",\"Medina\"]",
                            Text = "What is the capital of Saudi Arabia?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "London",
                            Options = "[\"Delhi\",\"London\",\"Berlin\",\"Rome\"]",
                            OptionsJson = "[\"Delhi\",\"London\",\"Berlin\",\"Rome\"]",
                            Text = "What is the capital of UK?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "Mars",
                            Options = "[\"Earth\",\"Mars\",\"Jupiter\",\"Saturn\"]",
                            OptionsJson = "[\"Earth\",\"Mars\",\"Jupiter\",\"Saturn\"]",
                            Text = "Which planet is known as the Red Planet?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
